import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <body className="min-h-screen bg-gray-50">
        <div className="flex min-h-screen">
          {/* Sidebar */}
          <aside className="w-24 shrink-0 border-r bg-white p-4">Sidebar</aside>

          {/* Content */}
          <main className="flex-1">
            <div className="flex min-h-screen items-center justify-center">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
